/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ClHi6WGVLdQ
 */
import { Button } from "@/components/ui/button"
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"

export function dashboardcards() {
  return (
    <div className="min-h-screen bg-[#121212] flex">
      <aside className="w-64 bg-[#1E1E1E] p-5">
        <div className="flex items-center space-x-2 mb-10">
          <AppWindowIcon className="text-white h-6 w-6" />
          <span className="text-white text-lg font-semibold">Govern Analysis</span>
        </div>
        <nav className="space-y-1">
          <a className="flex items-center space-x-2 p-2 text-white bg-[#333333] rounded-md" href="#">
            <HomeIcon className="h-5 w-5" />
            <span>Home</span>
          </a>
          <a className="flex items-center space-x-2 p-2 text-white hover:bg-[#333333] rounded-md" href="#">
            <TextIcon className="h-5 w-5" />
            <span>Chat</span>
          </a>
          <a className="flex items-center space-x-2 p-2 text-white hover:bg-[#333333] rounded-md" href="#">
            <ActivityIcon className="h-5 w-5" />
            <span>Assessment</span>
          </a>
          <a className="flex items-center space-x-2 p-2 text-white hover:bg-[#333333] rounded-md" href="#">
            <ServerIcon className="h-5 w-5" />
            <span>Services</span>
          </a>
          <a className="flex items-center space-x-2 p-2 text-white hover:bg-[#333333] rounded-md" href="#">
            <PowerIcon className="h-5 w-5" />
            <span>Resources</span>
          </a>
        </nav>
      </aside>
      <main className="flex-1 p-10">
        <h1 className="text-4xl text-white font-bold mb-4">Welcome to SME Portal</h1>
        <p className="text-white mb-6">
          SME Portal is the go-to platform for businesses to access government services and support. It provides a range
          of resources and tools to help SMEs grow and thrive.
        </p>
        <Button className="bg-white text-black">Assessment Tool</Button>
        <div className="mt-10 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          <Card className="bg-[#333333] text-white">
            <CardHeader>
              <CardTitle>Government Services</CardTitle>
              <CardDescription>
                Access a variety of services offered by the government to support your business.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <Button className="bg-white text-black">Learn More</Button>
            </CardContent>
          </Card>
          <Card className="bg-[#333333] text-white">
            <CardHeader>
              <CardTitle>Resource Center</CardTitle>
              <CardDescription>
                Find articles, tools, and guides to help you navigate through business challenges.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <Button className="bg-white text-black">Explore Resources</Button>
            </CardContent>
          </Card>
        </div>
      </main>
    </div>
  )
}


function AppWindowIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect x="2" y="4" width="20" height="16" rx="2" />
      <path d="M10 4v4" />
      <path d="M2 8h20" />
      <path d="M6 4v4" />
    </svg>
  )
}


function HomeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  )
}


function TextIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17 6.1H3" />
      <path d="M21 12.1H3" />
      <path d="M15.1 18H3" />
    </svg>
  )
}


function ActivityIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 12h-4l-3 9L9 3l-3 9H2" />
    </svg>
  )
}


function ServerIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="8" x="2" y="2" rx="2" ry="2" />
      <rect width="20" height="8" x="2" y="14" rx="2" ry="2" />
      <line x1="6" x2="6.01" y1="6" y2="6" />
      <line x1="6" x2="6.01" y1="18" y2="18" />
    </svg>
  )
}


function PowerIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18.36 6.64a9 9 0 1 1-12.73 0" />
      <line x1="12" x2="12" y1="2" y2="12" />
    </svg>
  )
}
